// <auto-generated />
using System;
using IntegrationMapper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationMapper.Infrastructure.Migrations
{
    [DbContext(typeof(IntegrationMapperContext))]
    [Migration("20260102190339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationMapper.Core.Entities.DataObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("DataObjects");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.FieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataObjectId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExampleValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DataObjectId");

                    b.HasIndex("ParentFieldId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceFieldId")
                        .HasColumnType("int");

                    b.Property<int>("TargetFieldId")
                        .HasColumnType("int");

                    b.Property<string>("TransformationLogic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceFieldId");

                    b.HasIndex("TargetFieldId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.IntegrationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("IntegrationSystems");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.MappingProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SourceObjectId")
                        .HasColumnType("int");

                    b.Property<int>("TargetObjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceObjectId");

                    b.HasIndex("TargetObjectId");

                    b.ToTable("MappingProjects");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.DataObject", b =>
                {
                    b.HasOne("IntegrationMapper.Core.Entities.IntegrationSystem", "System")
                        .WithMany("DataObjects")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.FieldDefinition", b =>
                {
                    b.HasOne("IntegrationMapper.Core.Entities.DataObject", "DataObject")
                        .WithMany("Fields")
                        .HasForeignKey("DataObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrationMapper.Core.Entities.FieldDefinition", "ParentField")
                        .WithMany("Children")
                        .HasForeignKey("ParentFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataObject");

                    b.Navigation("ParentField");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.FieldMapping", b =>
                {
                    b.HasOne("IntegrationMapper.Core.Entities.MappingProject", "Project")
                        .WithMany("Mappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrationMapper.Core.Entities.FieldDefinition", "SourceField")
                        .WithMany()
                        .HasForeignKey("SourceFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntegrationMapper.Core.Entities.FieldDefinition", "TargetField")
                        .WithMany()
                        .HasForeignKey("TargetFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SourceField");

                    b.Navigation("TargetField");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.MappingProject", b =>
                {
                    b.HasOne("IntegrationMapper.Core.Entities.DataObject", "SourceObject")
                        .WithMany()
                        .HasForeignKey("SourceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegrationMapper.Core.Entities.DataObject", "TargetObject")
                        .WithMany()
                        .HasForeignKey("TargetObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceObject");

                    b.Navigation("TargetObject");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.DataObject", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.FieldDefinition", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.IntegrationSystem", b =>
                {
                    b.Navigation("DataObjects");
                });

            modelBuilder.Entity("IntegrationMapper.Core.Entities.MappingProject", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
